---
title: "Heavy-tailed recruitment sims"
author: "Sean Anderson"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(DLMtool)
library(gfdlm)
library(rtails)
library(here)
library(MSEtool)
```

```{r example-om}
om <- new("OM", Rockfish, Generic_Fleet, Generic_Obs, Perfect_Imp)

om@nsim
om@nsim <- 10 # fewer simulations for faster runs
om@maxage
om@proyears
om@nyears

# Creating Perr_y matrix
# dim = c(nsim, maxage+proyears+nyears-1)
Perr_y <- matrix(
  data = 1, nrow = om@nsim,
  ncol = om@maxage + om@nyears + om@proyears - 1
)
dim(Perr_y)
Perr_y_rt <- Perr_y
Perr_y_rnorm <- Perr_y

(Perr <- mean(om@Perr))

# for (i in seq_len(om@nsim)) {
#   # historical:
#   Perr_y_rt[i, seq(1, om@maxage + om@nyears)] <- 
#     rst_tails(n = om@maxage + om@nyears, df = 1e6, scale = Perr, seed = i,
#       bias_correct = TRUE)
#   # projection:
#   Perr_y_rt[i, seq(om@maxage + om@nyears + 1, ncol(Perr_y))] <- 
#     rst_tails(n = ncol(Perr_y) - (om@maxage + om@nyears), 
#       df = 2.2, scale = Perr, seed = i * 28, bias_correct = TRUE)
# }
# for (i in seq_len(om@nsim)) {
#   # historical:
#   Perr_y_rnorm[i, seq(1, om@maxage + om@nyears)] <- 
#     rst_tails(n = om@maxage + om@nyears, df = 1e6, scale = Perr, seed = i,
#      bias_correct = TRUE)
#   # projection:
#   Perr_y_rnorm[i, seq(om@maxage + om@nyears + 1, ncol(Perr_y))] <- 
#     rst_tails(n = ncol(Perr_y) - (om@maxage + om@nyears), 
#       df = 1e6, scale = Perr, seed = i * 28, bias_correct = TRUE)
# }

# --------------------

black_swan_mult <- 10
black_swan_rate <- 1/20
skew <- 200 # heavily upward skewed
seed_mult <- 12938

rnt <- rnorm_tails(500, sigma = 0.2, high_sigma = 2, rate = 1/20, skew = 200, bias_correct = F, sample_bias_correct = T);plot_tails(rnt, log = T);mean(rnt)

for (i in seq_len(om@nsim)) {
  # historical:
  Perr_y_rt[i, seq(1, om@maxage + om@nyears)] <- 
    rnorm_tails(n = om@maxage + om@nyears,
      sigma = Perr, 
      high_sigma = Perr * 1.000000001,
      rate = black_swan_rate,
      skew = 0,
      seed = i,
      bias_correct = F,
      sample_bias_correct = T
    )
  # projection:
  Perr_y_rt[i, seq(om@maxage + om@nyears + 1, ncol(Perr_y))] <- 
    rnorm_tails(n = ncol(Perr_y) - (om@maxage + om@nyears),
      sigma = Perr, 
      high_sigma = Perr * black_swan_mult,
      rate = black_swan_rate,
      skew = skew,
      seed = i * seed_mult,
      bias_correct = F,
      sample_bias_correct = T
    )
}
for (i in seq_len(om@nsim)) {
  # historical:
  Perr_y_rnorm[i, seq(1, om@maxage + om@nyears)] <- 
    rnorm_tails(n = om@maxage + om@nyears,
      sigma = Perr, 
      high_sigma = Perr * 1.00000001,
      skew = 0,
      rate = black_swan_rate,
      seed = i,
      bias_correct = F,
      sample_bias_correct = T
    )
  # projection:
  Perr_y_rnorm[i, seq(om@maxage + om@nyears + 1, ncol(Perr_y))] <- 
    rnorm_tails(n = ncol(Perr_y) - (om@maxage + om@nyears),
      sigma = Perr, 
      high_sigma = Perr * 1.00000001,
      skew = 0,
      rate = black_swan_rate,
      seed = i * seed_mult,
      bias_correct = F,
      sample_bias_correct = T
    )
}

# recdevs_rt_eg <- rst_tails(n = om@nsim * om@proyears, df = 3, scale = .8,
#   seed = 123, bias_correct = TRUE)
# plot_tails(recdevs_rt_eg)
# plot_tails(recdevs_rt_eg, log = TRUE)

samps <- 5:9
all <- as.numeric(Perr_y_rt[samps,], Perr_y_rnorm[samps,])
par(mfcol = c(2, 2))
matplot(t(Perr_y_rt[samps,]), type = "l", lty  = 1, ylim = range(all))
abline(v = om@maxage + om@nyears, lty = 2, lwd = 2)
matplot(t(Perr_y_rnorm[samps,]), type = "l", lty  = 1, ylim = range(all))
abline(v = om@maxage + om@nyears, lty = 2, lwd = 2)

matplot(t(Perr_y_rt[samps,]), type = "l", lty  = 1, ylim = range(all), log = "y")
abline(v = om@maxage + om@nyears, lty = 2, lwd = 2)
matplot(t(Perr_y_rnorm[samps,]), type = "l", lty  = 1, ylim = range(all), log = "y")
abline(v = om@maxage + om@nyears, lty = 2, lwd = 2)

# recdevs_rnorm <- rst_tails(n = om@nsim * om@proyears, df = 1e6, scale = 0.8,
#   seed = 123)
# plot_tails(recdevs_rnorm)
# plot_tails(recdevs_rnorm, log = TRUE)
# 

om_rt <- om # copying om
om_rnorm <- om # copying om
om_rt@cpars <- list(Perr_y = Perr_y_rt)
om_rnorm@cpars <- list(Perr_y = Perr_y_rnorm)
```

MPs:

```{r}
reference_mp <- c("FMSYref75", "NFref", "FMSYref")
source(here("analysis", "define-mps.R"))

mp <- suppressMessages(readr::read_csv(here("analysis", "mp.txt"), comment = "#"))
# as.data.frame(mp) # look good?

mp <- c(
  "CC1.2", "CC1.1", "CC1.0", "CC0.9", "CC0.8", "CC0.7", "CC0.6", 
  # ".Iratio2", 
  # ".GB_slope6_0.66", ".GB_slope6_1", ".GB_slope8_0.66", ".GB_slope8_1",
  "GB_slope", "Islope1", "SP_4010",
  # ".Islope0.2_80", ".Islope0.2_100", ".Islope0.4_80", ".Islope0.4_100", 
  # ".IDX", ".IDX_smooth", 
  # ".IT10_hist", ".IT5_hist",
  # ".Itarget_base", ".Itarget_w0.8", ".Itarget_x0.2", ".Itarget_x0.8", ".Itarget_d1.2", ".Itarget_d0.8", 
  # ".ITM_hist",
  # ".SP6040_0.4", ".SP6040_0.5", ".SP6040_0.6", ".SP8040_0.6", ".SP4010_0.6", ".SP6040_0.6_fox",
  "NFref", "FMSYref", "FMSYref75")
```

PMs:

```{r}
`LT LRP` <- gfdlm::pm_factory("SBMSY", 0.4, c(36, 50))
`LT USR` <- gfdlm::pm_factory("SBMSY", 0.8, c(36, 50))
FMSY <- DLMtool::PNOF
STC <- gfdlm::pm_factory("LTY", 1, c(1, 10))
LTC <- gfdlm::pm_factory("LTY", 1, c(36, 50))
# AADC <- gfdlm::pm_factory("AADC", ref_aadc, c(1, 50))
# PM <- c("LT LRP", "LT USR", "FMSY", "STC", "LTC", "AADC")
PM <- c("LT LRP", "LT USR", "FMSY", "STC", "LTC")
```

Run the MSEs:

```{r runmse, eval=TRUE}
.parallel <- FALSE
# om@nsim <- 5
# om_rt@nsim <- 5
# om_rnorm@nsim <- 5
mp <- c("GB_slope", "Islope1", "SP_4010", "CC1.0", "CC0.8", "NFref", "FMSYref")
mse_rt <- runMSE(OM = om_rt, MPs = mp, parallel = .parallel)
mse_rnorm <- runMSE(OM = om_rnorm, MPs = mp, parallel = .parallel)
# mse_test <- runMSE(OM = om, MPs = mp, parallel = .parallel)
```

```{r}
gfdlm::plot_convergence(mse_rt, pm_list = PM)
gfdlm::plot_convergence(mse_rnorm, pm_list = PM)
```

```{r}
gfdlm::plot_index(mse_rt, n_samples = 3)
gfdlm::plot_index(mse_rnorm, n_samples = 3)
```

```{r}
# gfdlm::plot_main_projections(mse_test)
gfdlm::plot_main_projections(mse_rt)
gfdlm::plot_main_projections(mse_rnorm)
```

